var a,b={};b.prototype={q:function(){b.W();setInterval(b.prototype.r,15);b.G=0},r:function(){var d=(new Date).getTime();if(b.h!=0)b.l=d-b.h;b.h=d;b.G+=b.l;b.prototype.s();b.prototype.p()},s:function(){b.update();b.A=b.d;b.C=b.e},p:function(){b.a==0&&b.N()},k:function(d,e){b.o!=void 0&&b.o(d,e);b.canvas.width=d;b.canvas.height=e;a.I=b.canvas.width;a.H=b.canvas.height}};b.h=0;b.l=0;b.a=0;
b.Q=function(){this.canvas=$("#webgl-canvas")[0];try{a=this.canvas.getContext("experimental-webgl"),a.I=b.width=this.canvas.width,a.H=b.height=this.canvas.height,this.K="none",g(),a.clearDepth(1),a.enable(a.DEPTH_TEST),a.depthFunc(a.LEQUAL),this.prototype.q()}catch(d){alert(d)}a?b.prototype.k($(window).width(),$(window).height()):alert("Could not initialise WebGL, sorry :-(")};$(window).o(function(){b.prototype.k($(window).width(),$(window).height())});
SaitoShader=function(d,e){$.u({beforeSend:function(c){c.overrideMimeType&&c.overrideMimeType("text/plain")}});var c=this;b.a++;$.t({url:d,F:function(f){b.a--;f?(b.a++,$.u({beforeSend:function(c){c.overrideMimeType&&c.overrideMimeType("text/plain")}}),$.t({url:e,F:function(e){b.a--;e?(c.b=a.createShader(a.VERTEX_SHADER),c.b?(a.shaderSource(c.b,f),a.compileShader(c.b),a.getShaderParameter(c.b,a.COMPILE_STATUS)?(c.c=a.createShader(a.FRAGMENT_SHADER),c.b?(a.shaderSource(c.c,e),a.compileShader(c.c),a.getShaderParameter(c.c,
a.COMPILE_STATUS)?(c.i=a.createProgram(),a.attachShader(c.i,c.b),a.attachShader(c.i,c.c),a.linkProgram(c.i)):alert(a.getShaderInfoLog(c.c))):alert("No Shader Object could be created!")):alert(a.getShaderInfoLog(c.b))):alert("No Shader Object could be created!")):alert("Data file "+d+"was empty!")},error:function(){alert("Error loading "+d);b.a--}})):alert("Data file "+d+"was empty!")},error:function(){alert("Error loading "+d);b.a--}})};
SaitoTexture=function(d){this.j=new Image;this.g=a.createTexture();this.g.v=this.j;this.j.src=d;b.a++;var e=this;this.j.onload=function(){b.a--;a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!0);a.bindTexture(a.TEXTURE_2D,e.g);a.texImage2D(a.TEXTURE_2D,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,e.g.v);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.generateMipmap(a.TEXTURE_2D);a.bindTexture(a.TEXTURE_2D,null)}};
SaitoTextureCube=function(d,e){this.g=a.createTexture();this.f=[];for(var c=this.m=0;c<6;++c){this.f[c]=new Image;b.a++;this.f[c].M=c;var f=this;this.f[c].onload=function(){f.m++;b.a--;if(f.m==6){a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,!0);a.bindTexture(a.TEXTURE_CUBE_MAP,f.g);a.texParameteri(a.TEXTURE_CUBE_MAP,a.TEXTURE_MAG_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_CUBE_MAP,a.TEXTURE_MIN_FILTER,a.LINEAR);a.texParameteri(a.TEXTURE_CUBE_MAP,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_CUBE_MAP,
a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);for(var c=0;c<6;++c)a.texImage2D(a.TEXTURE_CUBE_MAP_POSITIVE_X+c,0,a.RGBA,a.RGBA,a.UNSIGNED_BYTE,f.f[c]);a.bindTexture(a.TEXTURE_CUBE_MAP,null)}};this.f[c].src=d+"_0"+c+"."+e}};
function g(){b.d=0;b.e=0;b.A=0;b.C=0;b.B=0;b.D=0;b.n=!1;$(b.canvas).S(function(d){var e=$(b.canvas).position();b.d=d.pageX-e.left;b.e=d.pageY-e.top;b.d-=b.canvas.width/2;b.e-=b.canvas.height/2;b.d/=b.canvas.width/2;b.e/=b.canvas.height/2});$(b.canvas).R(function(){b.n=!0;b.B=b.d;b.D=b.e});$(b.canvas).T(function(){b.n=!1});$(b.canvas).U(function(d,e){e>0?b.z!=void 0&&b.z():e<0&&b.w!=void 0&&b.w()})}Colour=function(d,e,c,f){this.V=d;this.O=e;this.L=c;this.J=f};
Size2=function(d,e){this.Y=d;this.P=e;this.X=$V([d,e])};

